# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.cache/wt [current_project]
set_property parent.project_path /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.runs/clk_wiz_synth_1/clk_wiz.dcp
set_property used_in_implementation false [get_files /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.runs/clk_wiz_synth_1/clk_wiz.dcp]
read_verilog -library xil_defaultlib {
  /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/sources_1/imports/FPGALab4/library.v
  /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/sources_1/imports/FPGALab4/register.v
  /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/sources_1/new/counter_three.v
  /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/sources_1/new/counter_odd.v
  /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/sources_1/imports/FPGALab4/counter_even.v
  /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/sources_1/imports/src/clock_divider.v
  /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/sources_1/imports/FPGALab4/bcd2led.v
  /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/sources_1/imports/FPGALab4/counter_natural.v
  /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/sources_1/new/top_level.v
}
read_xdc /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/constrs_1/imports/FPGALab4/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/hequ2/cs233/hequ2/fpgalab4_fsm/fpgalab4_fsm.srcs/constrs_1/imports/FPGALab4/Basys3_Master.xdc]

synth_design -top top_level -part xc7a35tcpg236-1
write_checkpoint -noxdef top_level.dcp
catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
